image:
  file: .gitpod.Dockerfile
  
  
tasks:
  -  init:pip install tf-nightly                                                   &&
          pip install tensorflowjs                                                 &&
          pip install netron                                                       &&
          cd myFolder                                                              &&
          chmod +x a01-go.sh                                                       &&      
          ./a01-go.sh                                                              
                                                                                   

              
