image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: pip install tf-nightly                                                   &&
          pip install tensorflowjs                                                 &&
          pip install netron                                                       &&
          cd myFolder                                                              &&
          chmod +x a01-convert-tfjs-arduino.sh                                     &&      
          ./a01-convert-tfjs-arduino.sh                                                             
                                                                                   

              
