image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: pip install tf-nightly                                                   &&
          pip install tensorflowjs                                                 &&
          pip install netron                                                       &&
          cd myExample                                                             &&
          chmod +x a01-convert-tfjs-arduino.sh                                     && 
          ./a01-convert-tfjs-arduino.sh                                            &&                                             
          cd ..                                                                    &&
          cd myFolder                                                              &&
          tflite_convert --help                                                    &&
          tensorflowjs_converter --help                                            &&
          xxd --help                                                               &&
          echo "upload your model.json and model.weights.bin files here then run ./a01-convert-tfjs-arduino.sh"                                                                                                                          

              
